name: Go

on:
  push:
    branches: [ "raghug/init" ]
  pull_request:
    branches: [ "raghug/init" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
      - name: Build
        run: go build -v ./...
      - name: Test with Coverage
        run: go test -v -coverpkg=./... -coverprofile=coverage.out ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: raghuganapathyUCR/arcgis-sdk
