name: release with coverage on main branch

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]  # Trigger the workflow on tag pushes that match the 'v*' pattern (e.g., v1.0.0)
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
      - name: Build
        run: go build -v ./...
      - name: Test with Coverage
        run: go test -v -coverpkg=./... -coverprofile=coverage.out ./...
        env: # Set the environment variable for the test
          ARCGIS_KEY: ${{ secrets.ARCGIS_KEY }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: raghuganapathyUCR/arcgis-sdk
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')  # Only run this step if the push is a tag with the 'v' prefix
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
